swagger: "2.0"
info:
  title: Case Swrs
  version: 1.0.0

paths:
  /search:
    get:
      operationId: search
      x-google-backend:
        address: https://.cloudfunctions.net/search
      security:
        - api_key: []

  /film-relations:
    get:
      operationId: film_relations
      x-google-backend:
        address: https://.cloudfunctions.net/film_relations
      security:
        - api_key: []

securityDefinitions:
  api_key:
    type: apiKey
    name: x-api-key
    in: header